function imageWriter(image,name,ROI_y_pix,ROI_x_pix)
imwrite(...
    uint8(...
        sqrt(...
            abs(...
                image(ROI_y_pix(1):ROI_y_pix(2),ROI_x_pix(1):ROI_x_pix(2))...
            )...
        )...
    )...
,name+".png", 'BitDepth', 8);