function imageWriterMod(image,name)

I = sqrt(abs(image));
% J = imadjust(I,stretchlim(I),[0 1]);
J = I./max(I);
% J = mat2gray(I, [0,255]);
J = J.*255;
cm = colormap('gray');
cm = colormap(cm(end:-1:1,:));
% imagesc(sqrt(abs(image)))
% imageIND = double(image) - double(min(image(:)));
% imageIND = imageIND / max(imageIND(:));
imwrite(...
    uint8(...
        sqrt(...
            abs(...
                J...
            )...
        )...
    )...
,cm,name+".png");
% gray,name+".png", 'BitDepth', 8);