function imageWriter(image,name,ROI_y_pix,ROI_x_pix)
cm = colormap('gray');
cm = colormap(cm(end:-1:1,:));
% imagesc(sqrt(abs(image)))
% imageIND = double(image) - double(min(image(:)));
% imageIND = imageIND / max(imageIND(:));
imwrite(...
    uint8(...
        sqrt(...
            abs(...
                image(ROI_y_pix(1):ROI_y_pix(2),ROI_x_pix(1):ROI_x_pix(2))...
            )...
        )...
    )...
,cm,name+".png", 'BitDepth', 8);